server.port: 8081
spring.autoconfigure.exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
openai:
  model: gpt-3.5-turbo
  api:
    url: https://api.openai.com/v1/chat/completions
    key: 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

socket:
  port: 8082
  host: localhost
